### ISSUE TITLE
snmpwalk(): Invalid object identifier

### ISSUE THREAD

**Issue by abidhamma** [xeleniumz/zte-libraries-php#1]
snmpwalk(): Invalid object identifier: 1.3.6.1.4.1.2.2.1.8.STRING: "ZXAN" \Kernel\Snmp\Olt.php on line 59

Hello

I tried your lib.. but i got this error... how to fix this? how to get object id for zte? Thanks

**Comment by xeleniumz** [comment]
Sorry for late reply. Do you test with snmp walk command in your terminal ?

**Comment by abidhamma** [comment]
Yes.. its work well... how can you get Object Identifier for OLT? do you have list of it? thanks

**Comment by xeleniumz** [comment]
I got it from ZTE monitor software. I can't remember software name but it is desktop application ( windows )

**Comment by abidhamma** [comment]
Thanks for your information. I try to fix it...
